### ISSUE TITLE
Seems to be broken with the release 23.10

### ISSUE THREAD

**Issue by Noobgam** [Quip13/Anki-Zoom#22]
The stack trace:

```
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10 (51a10f09) Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-01 12:43:38
Add-ons possibly involved: ⁨Anki Zoom⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.toolbar", line 67, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.toolbar", line 187, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.toolbar", line 67, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.toolbar", line 187, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\Noobgam\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'
```

Disabling the anki zoom helps, but it's a necessary addon for me :(

**Comment by Noobgam** [comment]
Nevermind with 23.10 this addon is obsolete, not sure since when but anki natively supports zooming already.
