### ISSUE TITLE
7 error windows and different zoom amount

### ISSUE THREAD

**Issue by kudosscience** [Quip13/Anki-Zoom#23]
On Anki startup, 7 Anki error windows open in a cascade.

Opening Anki with add-ons disabled avoids the error windows but the zoom is still set differently from how I had it previously.

Error window message appears as:

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22631
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-17 20:43:11
Add-ons possibly involved: ⁨Anki Zoom⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 148, in eventFilter
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 83, in repl
  File "C:\Users\henry\AppData\Roaming\Anki2\addons21\538879081\__init__.py", line 107, in AnkiWebView_eventFilter_wrapper
    if (mw.app.keyboardModifiers() == Qt.ControlModifier and
AttributeError: type object 'Qt' has no attribute 'ControlModifier'

**Comment by nclvrps** [comment]
This particular error would be solved by changing Qt.ControlModifier to Qt.KeyboardModifier.ControlModifier (the change is backwards compatible).

See https://doc.qt.io/qt-6/qt.html and https://forums.ankiweb.net/t/porting-tips-for-anki-23-10/35916
